package com.mj.travel.dao;

import com.mj.travel.entity.TravelCar;
import java.util.List;

public interface TravelCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_car
     *
     * @mbg.generated Mon Sep 10 19:20:24 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_car
     *
     * @mbg.generated Mon Sep 10 19:20:24 CST 2018
     */
    int insert(TravelCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_car
     *
     * @mbg.generated Mon Sep 10 19:20:24 CST 2018
     */
    TravelCar selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_car
     *
     * @mbg.generated Mon Sep 10 19:20:24 CST 2018
     */
    List<TravelCar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_car
     *
     * @mbg.generated Mon Sep 10 19:20:24 CST 2018
     */
    int updateByPrimaryKey(TravelCar record);
}