package com.mj.travel.dao;

import com.mj.travel.entity.TravelHotel;
import java.util.List;

public interface TravelHotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    int insert(TravelHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    TravelHotel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    List<TravelHotel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    int updateByPrimaryKey(TravelHotel record);
}