package com.mj.travel.dao;

import com.mj.travel.entity.TravelFood;
import java.util.List;

public interface TravelFoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_food
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_food
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    int insert(TravelFood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_food
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    TravelFood selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_food
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    List<TravelFood> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_food
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    int updateByPrimaryKey(TravelFood record);
}