package com.mj.travel.dao;

import com.mj.travel.entity.TravelShopping;
import java.util.List;

public interface TravelShoppingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_shopping
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_shopping
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    int insert(TravelShopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_shopping
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    TravelShopping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_shopping
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    List<TravelShopping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_shopping
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    int updateByPrimaryKey(TravelShopping record);
}