package com.mj.travel.dao;

import com.mj.travel.entity.TravelDestination;
import java.util.List;

public interface TravelDestinationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_destination
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_destination
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    int insert(TravelDestination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_destination
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    TravelDestination selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_destination
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    List<TravelDestination> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_destination
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    int updateByPrimaryKey(TravelDestination record);
}