package com.mj.travel.dao;

import com.mj.travel.entity.TravelTourist;
import java.util.List;

public interface TravelTouristMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_tourist
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_tourist
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    int insert(TravelTourist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_tourist
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    TravelTourist selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_tourist
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    List<TravelTourist> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_tourist
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    int updateByPrimaryKey(TravelTourist record);
}