server:
  port: 1111
spring:
  application:
    name: server-service

eureka.instance.prefer-ip-address: true
#2.0新特性spring.cloud.client.ip-address
eureka.instance.instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
eureka.client.serviceUrl.defaultZone: http://root:root@localhost:9999/eureka/

