server:
  port: 1111
spring:
  application:
    name: travel-service
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver


# Mybatis
mybatis.type-aliases-package: com.mj.travel.entity
mybatis.mapper-locations: classpath:com/mj/travel/mapper/*.xml


#eureka.client. healthcheck. enabled: true                           # 开启健康检查（依赖spring-boot-starter-actuator）