server:
  port: 1111
spring:
  application:
    name: server-service


#eureka.client. healthcheck. enabled: true                           # 开启健康检查（依赖spring-boot-starter-actuator）

#
#spring.cloud.config.name: service
#spring.cloud.config.discovery.enabled: true
#spring.cloud.config.discovery.service-id: config-service
#spring.cloud.config.profile: dev