package com.mj.springcloudserver.dao;

import com.mj.springcloudserver.entity.AcBank;
import java.util.List;

public interface AcBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_bank
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_bank
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    int insert(AcBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_bank
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    AcBank selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_bank
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    List<AcBank> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_bank
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    int updateByPrimaryKey(AcBank record);


}
