package com.mj.springcloudserver.entity;

import java.util.Date;

public class AcBank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.id
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.member_id
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.account_source
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private Integer accountSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.bank_area_code
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String bankAreaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.bank_name_code
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String bankNameCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.bank_name
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.bank_no
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String bankNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.bank_status
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String bankStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.bind_time
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private Date bindTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.card_type
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.is_def
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private Integer isDef;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.create_user
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.create_time
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.update_user
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.update_time
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.remarks
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_bank.del_flag
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.id
     *
     * @return the value of ac_bank.id
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.id
     *
     * @param id the value for ac_bank.id
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.member_id
     *
     * @return the value of ac_bank.member_id
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.member_id
     *
     * @param memberId the value for ac_bank.member_id
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.account_source
     *
     * @return the value of ac_bank.account_source
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public Integer getAccountSource() {
        return accountSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.account_source
     *
     * @param accountSource the value for ac_bank.account_source
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setAccountSource(Integer accountSource) {
        this.accountSource = accountSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.bank_area_code
     *
     * @return the value of ac_bank.bank_area_code
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getBankAreaCode() {
        return bankAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.bank_area_code
     *
     * @param bankAreaCode the value for ac_bank.bank_area_code
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setBankAreaCode(String bankAreaCode) {
        this.bankAreaCode = bankAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.bank_name_code
     *
     * @return the value of ac_bank.bank_name_code
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getBankNameCode() {
        return bankNameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.bank_name_code
     *
     * @param bankNameCode the value for ac_bank.bank_name_code
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setBankNameCode(String bankNameCode) {
        this.bankNameCode = bankNameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.bank_name
     *
     * @return the value of ac_bank.bank_name
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.bank_name
     *
     * @param bankName the value for ac_bank.bank_name
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.bank_no
     *
     * @return the value of ac_bank.bank_no
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.bank_no
     *
     * @param bankNo the value for ac_bank.bank_no
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.bank_status
     *
     * @return the value of ac_bank.bank_status
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getBankStatus() {
        return bankStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.bank_status
     *
     * @param bankStatus the value for ac_bank.bank_status
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setBankStatus(String bankStatus) {
        this.bankStatus = bankStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.bind_time
     *
     * @return the value of ac_bank.bind_time
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public Date getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.bind_time
     *
     * @param bindTime the value for ac_bank.bind_time
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setBindTime(Date bindTime) {
        this.bindTime = bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.card_type
     *
     * @return the value of ac_bank.card_type
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.card_type
     *
     * @param cardType the value for ac_bank.card_type
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.is_def
     *
     * @return the value of ac_bank.is_def
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public Integer getIsDef() {
        return isDef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.is_def
     *
     * @param isDef the value for ac_bank.is_def
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setIsDef(Integer isDef) {
        this.isDef = isDef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.create_user
     *
     * @return the value of ac_bank.create_user
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.create_user
     *
     * @param createUser the value for ac_bank.create_user
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.create_time
     *
     * @return the value of ac_bank.create_time
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.create_time
     *
     * @param createTime the value for ac_bank.create_time
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.update_user
     *
     * @return the value of ac_bank.update_user
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.update_user
     *
     * @param updateUser the value for ac_bank.update_user
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.update_time
     *
     * @return the value of ac_bank.update_time
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.update_time
     *
     * @param updateTime the value for ac_bank.update_time
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.remarks
     *
     * @return the value of ac_bank.remarks
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.remarks
     *
     * @param remarks the value for ac_bank.remarks
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_bank.del_flag
     *
     * @return the value of ac_bank.del_flag
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_bank.del_flag
     *
     * @param delFlag the value for ac_bank.del_flag
     *
     * @mbg.generated Mon Sep 10 09:34:52 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    @Override
    public String toString() {
        return "AcBank{" +
                "id='" + id + '\'' +
                ", memberId='" + memberId + '\'' +
                ", accountSource=" + accountSource +
                ", bankAreaCode='" + bankAreaCode + '\'' +
                ", bankNameCode='" + bankNameCode + '\'' +
                ", bankName='" + bankName + '\'' +
                ", bankNo='" + bankNo + '\'' +
                ", bankStatus='" + bankStatus + '\'' +
                ", bindTime=" + bindTime +
                ", cardType='" + cardType + '\'' +
                ", isDef=" + isDef +
                ", createUser='" + createUser + '\'' +
                ", createTime=" + createTime +
                ", updateUser='" + updateUser + '\'' +
                ", updateTime=" + updateTime +
                ", remarks='" + remarks + '\'' +
                ", delFlag=" + delFlag +
                '}';
    }
}