package com.mj.travel.entity;

import java.util.Date;

public class TravelTourist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.id
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.destination_id
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private String destinationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.tourist_name
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private String touristName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.tourist_star
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private String touristStar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.total_hours
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private Double totalHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.date
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.price
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.count
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.mark
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private Double mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.description
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.source
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.remark
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.create_user
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.update_user
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.create_time
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_tourist.update_time
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.id
     *
     * @return the value of travel_tourist.id
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.id
     *
     * @param id the value for travel_tourist.id
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.destination_id
     *
     * @return the value of travel_tourist.destination_id
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public String getDestinationId() {
        return destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.destination_id
     *
     * @param destinationId the value for travel_tourist.destination_id
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setDestinationId(String destinationId) {
        this.destinationId = destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.tourist_name
     *
     * @return the value of travel_tourist.tourist_name
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public String getTouristName() {
        return touristName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.tourist_name
     *
     * @param touristName the value for travel_tourist.tourist_name
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setTouristName(String touristName) {
        this.touristName = touristName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.tourist_star
     *
     * @return the value of travel_tourist.tourist_star
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public String getTouristStar() {
        return touristStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.tourist_star
     *
     * @param touristStar the value for travel_tourist.tourist_star
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setTouristStar(String touristStar) {
        this.touristStar = touristStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.total_hours
     *
     * @return the value of travel_tourist.total_hours
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public Double getTotalHours() {
        return totalHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.total_hours
     *
     * @param totalHours the value for travel_tourist.total_hours
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setTotalHours(Double totalHours) {
        this.totalHours = totalHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.date
     *
     * @return the value of travel_tourist.date
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.date
     *
     * @param date the value for travel_tourist.date
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.price
     *
     * @return the value of travel_tourist.price
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.price
     *
     * @param price the value for travel_tourist.price
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.count
     *
     * @return the value of travel_tourist.count
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.count
     *
     * @param count the value for travel_tourist.count
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.mark
     *
     * @return the value of travel_tourist.mark
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public Double getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.mark
     *
     * @param mark the value for travel_tourist.mark
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setMark(Double mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.description
     *
     * @return the value of travel_tourist.description
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.description
     *
     * @param description the value for travel_tourist.description
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.source
     *
     * @return the value of travel_tourist.source
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.source
     *
     * @param source the value for travel_tourist.source
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.remark
     *
     * @return the value of travel_tourist.remark
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.remark
     *
     * @param remark the value for travel_tourist.remark
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.create_user
     *
     * @return the value of travel_tourist.create_user
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.create_user
     *
     * @param createUser the value for travel_tourist.create_user
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.update_user
     *
     * @return the value of travel_tourist.update_user
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.update_user
     *
     * @param updateUser the value for travel_tourist.update_user
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.create_time
     *
     * @return the value of travel_tourist.create_time
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.create_time
     *
     * @param createTime the value for travel_tourist.create_time
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_tourist.update_time
     *
     * @return the value of travel_tourist.update_time
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_tourist.update_time
     *
     * @param updateTime the value for travel_tourist.update_time
     *
     * @mbg.generated Mon Sep 10 19:22:49 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}