package com.mj.travel.entity;

import java.util.Date;

public class TravelTrain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.id
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.destination_id
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private String destinationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.train_num
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private String trainNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.origin
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.terminus
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private String terminus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.total_hours
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private Double totalHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.price
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.count
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.remark
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.create_user
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.update_user
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.create_time
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_train.update_time
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.id
     *
     * @return the value of travel_train.id
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.id
     *
     * @param id the value for travel_train.id
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.destination_id
     *
     * @return the value of travel_train.destination_id
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public String getDestinationId() {
        return destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.destination_id
     *
     * @param destinationId the value for travel_train.destination_id
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setDestinationId(String destinationId) {
        this.destinationId = destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.train_num
     *
     * @return the value of travel_train.train_num
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public String getTrainNum() {
        return trainNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.train_num
     *
     * @param trainNum the value for travel_train.train_num
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setTrainNum(String trainNum) {
        this.trainNum = trainNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.origin
     *
     * @return the value of travel_train.origin
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.origin
     *
     * @param origin the value for travel_train.origin
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.terminus
     *
     * @return the value of travel_train.terminus
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public String getTerminus() {
        return terminus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.terminus
     *
     * @param terminus the value for travel_train.terminus
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setTerminus(String terminus) {
        this.terminus = terminus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.total_hours
     *
     * @return the value of travel_train.total_hours
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public Double getTotalHours() {
        return totalHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.total_hours
     *
     * @param totalHours the value for travel_train.total_hours
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setTotalHours(Double totalHours) {
        this.totalHours = totalHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.price
     *
     * @return the value of travel_train.price
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.price
     *
     * @param price the value for travel_train.price
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.count
     *
     * @return the value of travel_train.count
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.count
     *
     * @param count the value for travel_train.count
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.remark
     *
     * @return the value of travel_train.remark
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.remark
     *
     * @param remark the value for travel_train.remark
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.create_user
     *
     * @return the value of travel_train.create_user
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.create_user
     *
     * @param createUser the value for travel_train.create_user
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.update_user
     *
     * @return the value of travel_train.update_user
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.update_user
     *
     * @param updateUser the value for travel_train.update_user
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.create_time
     *
     * @return the value of travel_train.create_time
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.create_time
     *
     * @param createTime the value for travel_train.create_time
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_train.update_time
     *
     * @return the value of travel_train.update_time
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_train.update_time
     *
     * @param updateTime the value for travel_train.update_time
     *
     * @mbg.generated Mon Sep 10 19:23:07 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}