package com.mj.travel.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TravelFood {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.id
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.destination_id
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private String destinationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.food_type
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private String foodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.restaurant_name
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private String restaurantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.price
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.description
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.remark
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.create_user
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.update_user
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.create_time
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_food.update_time
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.id
     *
     * @return the value of travel_food.id
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.id
     *
     * @param id the value for travel_food.id
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.destination_id
     *
     * @return the value of travel_food.destination_id
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public String getDestinationId() {
        return destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.destination_id
     *
     * @param destinationId the value for travel_food.destination_id
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setDestinationId(String destinationId) {
        this.destinationId = destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.food_type
     *
     * @return the value of travel_food.food_type
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public String getFoodType() {
        return foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.food_type
     *
     * @param foodType the value for travel_food.food_type
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setFoodType(String foodType) {
        this.foodType = foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.restaurant_name
     *
     * @return the value of travel_food.restaurant_name
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public String getRestaurantName() {
        return restaurantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.restaurant_name
     *
     * @param restaurantName the value for travel_food.restaurant_name
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setRestaurantName(String restaurantName) {
        this.restaurantName = restaurantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.price
     *
     * @return the value of travel_food.price
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.price
     *
     * @param price the value for travel_food.price
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.description
     *
     * @return the value of travel_food.description
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.description
     *
     * @param description the value for travel_food.description
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.remark
     *
     * @return the value of travel_food.remark
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.remark
     *
     * @param remark the value for travel_food.remark
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.create_user
     *
     * @return the value of travel_food.create_user
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.create_user
     *
     * @param createUser the value for travel_food.create_user
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.update_user
     *
     * @return the value of travel_food.update_user
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.update_user
     *
     * @param updateUser the value for travel_food.update_user
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.create_time
     *
     * @return the value of travel_food.create_time
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.create_time
     *
     * @param createTime the value for travel_food.create_time
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_food.update_time
     *
     * @return the value of travel_food.update_time
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_food.update_time
     *
     * @param updateTime the value for travel_food.update_time
     *
     * @mbg.generated Mon Sep 10 19:21:47 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}