package com.mj.travel.entity;

import java.util.Date;

public class TravelHotel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.id
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.destination_id
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private String destinationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.hotel_name
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private String hotelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.hotel_type
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private String hotelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.start_date
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.count
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.price
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.mark
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private Double mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.description
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.source
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.remark
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.create_user
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.update_user
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.create_time
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel.update_time
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.id
     *
     * @return the value of travel_hotel.id
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.id
     *
     * @param id the value for travel_hotel.id
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.destination_id
     *
     * @return the value of travel_hotel.destination_id
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public String getDestinationId() {
        return destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.destination_id
     *
     * @param destinationId the value for travel_hotel.destination_id
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setDestinationId(String destinationId) {
        this.destinationId = destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.hotel_name
     *
     * @return the value of travel_hotel.hotel_name
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.hotel_name
     *
     * @param hotelName the value for travel_hotel.hotel_name
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.hotel_type
     *
     * @return the value of travel_hotel.hotel_type
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public String getHotelType() {
        return hotelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.hotel_type
     *
     * @param hotelType the value for travel_hotel.hotel_type
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setHotelType(String hotelType) {
        this.hotelType = hotelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.start_date
     *
     * @return the value of travel_hotel.start_date
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.start_date
     *
     * @param startDate the value for travel_hotel.start_date
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.count
     *
     * @return the value of travel_hotel.count
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.count
     *
     * @param count the value for travel_hotel.count
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.price
     *
     * @return the value of travel_hotel.price
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.price
     *
     * @param price the value for travel_hotel.price
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.mark
     *
     * @return the value of travel_hotel.mark
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public Double getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.mark
     *
     * @param mark the value for travel_hotel.mark
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setMark(Double mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.description
     *
     * @return the value of travel_hotel.description
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.description
     *
     * @param description the value for travel_hotel.description
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.source
     *
     * @return the value of travel_hotel.source
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.source
     *
     * @param source the value for travel_hotel.source
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.remark
     *
     * @return the value of travel_hotel.remark
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.remark
     *
     * @param remark the value for travel_hotel.remark
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.create_user
     *
     * @return the value of travel_hotel.create_user
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.create_user
     *
     * @param createUser the value for travel_hotel.create_user
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.update_user
     *
     * @return the value of travel_hotel.update_user
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.update_user
     *
     * @param updateUser the value for travel_hotel.update_user
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.create_time
     *
     * @return the value of travel_hotel.create_time
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.create_time
     *
     * @param createTime the value for travel_hotel.create_time
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel.update_time
     *
     * @return the value of travel_hotel.update_time
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel.update_time
     *
     * @param updateTime the value for travel_hotel.update_time
     *
     * @mbg.generated Mon Sep 10 19:22:09 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}