package com.mj.travel.entity;

import java.util.Date;

public class TravelDestination {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_destination.id
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_destination.destination_name
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    private String destinationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_destination.start_date
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_destination.total_day
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    private Integer totalDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_destination.vehicle_type
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    private String vehicleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_destination.remark
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_destination.create_user
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_destination.update_user
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_destination.create_time
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_destination.update_time
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_destination.id
     *
     * @return the value of travel_destination.id
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_destination.id
     *
     * @param id the value for travel_destination.id
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_destination.destination_name
     *
     * @return the value of travel_destination.destination_name
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public String getDestinationName() {
        return destinationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_destination.destination_name
     *
     * @param destinationName the value for travel_destination.destination_name
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public void setDestinationName(String destinationName) {
        this.destinationName = destinationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_destination.start_date
     *
     * @return the value of travel_destination.start_date
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_destination.start_date
     *
     * @param startDate the value for travel_destination.start_date
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_destination.total_day
     *
     * @return the value of travel_destination.total_day
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public Integer getTotalDay() {
        return totalDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_destination.total_day
     *
     * @param totalDay the value for travel_destination.total_day
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public void setTotalDay(Integer totalDay) {
        this.totalDay = totalDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_destination.vehicle_type
     *
     * @return the value of travel_destination.vehicle_type
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_destination.vehicle_type
     *
     * @param vehicleType the value for travel_destination.vehicle_type
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_destination.remark
     *
     * @return the value of travel_destination.remark
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_destination.remark
     *
     * @param remark the value for travel_destination.remark
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_destination.create_user
     *
     * @return the value of travel_destination.create_user
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_destination.create_user
     *
     * @param createUser the value for travel_destination.create_user
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_destination.update_user
     *
     * @return the value of travel_destination.update_user
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_destination.update_user
     *
     * @param updateUser the value for travel_destination.update_user
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_destination.create_time
     *
     * @return the value of travel_destination.create_time
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_destination.create_time
     *
     * @param createTime the value for travel_destination.create_time
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_destination.update_time
     *
     * @return the value of travel_destination.update_time
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_destination.update_time
     *
     * @param updateTime the value for travel_destination.update_time
     *
     * @mbg.generated Mon Sep 10 19:21:32 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "TravelDestination{" +
                "id='" + id + '\'' +
                ", destinationName='" + destinationName + '\'' +
                ", startDate=" + startDate +
                ", totalDay=" + totalDay +
                ", vehicleType='" + vehicleType + '\'' +
                ", remark='" + remark + '\'' +
                ", createUser='" + createUser + '\'' +
                ", updateUser='" + updateUser + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
}