package com.mj.travel.entity;

import java.util.Date;

public class TravelShopping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.id
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.destination_id
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private String destinationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.shopping_type
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private String shoppingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.trade_name
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private String tradeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.price
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.description
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.remark
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.create_user
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.update_user
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.create_time
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_shopping.update_time
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.id
     *
     * @return the value of travel_shopping.id
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.id
     *
     * @param id the value for travel_shopping.id
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.destination_id
     *
     * @return the value of travel_shopping.destination_id
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public String getDestinationId() {
        return destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.destination_id
     *
     * @param destinationId the value for travel_shopping.destination_id
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setDestinationId(String destinationId) {
        this.destinationId = destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.shopping_type
     *
     * @return the value of travel_shopping.shopping_type
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public String getShoppingType() {
        return shoppingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.shopping_type
     *
     * @param shoppingType the value for travel_shopping.shopping_type
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setShoppingType(String shoppingType) {
        this.shoppingType = shoppingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.trade_name
     *
     * @return the value of travel_shopping.trade_name
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public String getTradeName() {
        return tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.trade_name
     *
     * @param tradeName the value for travel_shopping.trade_name
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.price
     *
     * @return the value of travel_shopping.price
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.price
     *
     * @param price the value for travel_shopping.price
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.description
     *
     * @return the value of travel_shopping.description
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.description
     *
     * @param description the value for travel_shopping.description
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.remark
     *
     * @return the value of travel_shopping.remark
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.remark
     *
     * @param remark the value for travel_shopping.remark
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.create_user
     *
     * @return the value of travel_shopping.create_user
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.create_user
     *
     * @param createUser the value for travel_shopping.create_user
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.update_user
     *
     * @return the value of travel_shopping.update_user
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.update_user
     *
     * @param updateUser the value for travel_shopping.update_user
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.create_time
     *
     * @return the value of travel_shopping.create_time
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.create_time
     *
     * @param createTime the value for travel_shopping.create_time
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_shopping.update_time
     *
     * @return the value of travel_shopping.update_time
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_shopping.update_time
     *
     * @param updateTime the value for travel_shopping.update_time
     *
     * @mbg.generated Mon Sep 10 19:22:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}